services:
  app:
    build:
      context: .
      target: deploy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
    ports:
      - 3333:3333
    command: ["/usr/local/bin/pseudo-bank"]
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  integration-test:
    build:
      context: .
      target: build
    environment:
      - APP_URL=app:3333
    ports:
      - 3333:3333
    command: ["go", "test", "--tags=integration", "-v", "./..."]
    depends_on:
      - app

volumes:
  db-data: