services:
  app:
    build:
      context: .
      target: deploy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
    ports:
      - 3333:3333
    command: [ "/usr/local/bin/pseudo-bank" ]
    depends_on:
      - postgres
    profiles:
      - app
      - integration-test
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    profiles:
      - app
      - integration-test
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    profiles:
      - app
  integration-test:
    build:
      context: .
      target: build
    environment:
      - APP_URL=app:3333
    ports:
      - 3333:3333
    command: [ "go", "test", "--tags=integration", "-v", "./..." ]
    depends_on:
      - app
    profiles:
      - integration-test
  unit-test:
    build:
      context: .
      target: build
    command: [ "go", "test", "-v", "./..." ]
    profiles:
      - unit-test

volumes:
  db-data:
